services:
  app:
    image: todo-front-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
    container_name: todo-front-dev # This will name the container
  debug-helper:
    image: busybox
