services:
  app:
    image: todo-front-dev
    build:
      context: './todo-frontend' # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend/:/usr/src/app
    ports:
      - 3001:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
    container_name: todo-front-dev # This will name the container
  debug-helper:
    image: busybox
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.dev.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
